name: Deploy tests

on:
  pull_request:

concurrency:  # Cancel previous workflows on the same pull request
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run-tests:
    uses: catalystneuro/leifer-lab-to-nwb/.github/workflows/testing.yml@main

  check-final-status:
    name: All tests passing
    if: always()

    needs:
    - run-tests

    runs-on: ubuntu-latest

    steps:
    - name: Decide whether the all jobs succeeded or at least one failed
      uses: re-actors/alls-green@release/v1
      with:
        allowed-skips: run-tests  # Sometimes only docs are adjusted
        jobs: ${{ toJSON(needs) }}
